### ISSUE TITLE
Updating INSTRUCTIONS.md

### ISSUE THREAD

**Issue by twitu** [kandersen/dpc#5]
The current instructions to run the simulation interface is outdated or incorrect since there is no netsim target or package. Running `stack ide targets` gives the following output.

```
dpc:lib
dpc:exe:poly-client
dpc:exe:poly-server
```

However since `dpc:lib` does not export example modules `stack repl dpc:lib` will not help. Instead what worked for me was doing a `stack repl` and then loading nothing specific by pressing enter. This loaded all the modules in the project and let me run the examples.

Changing this section of the instructions

```
## Running The Simulation Interface

Once built, load all the core libraries and examples:

$ stack repl netsim:lib

Then run the simulator of the corresponding distributed application as follows:

> runGUI NetSim.Examples.AppName.initNetwork

where `AppName` is, e.g., `Calculator.Calculator` or `DistributedLocking`. Use digits `1-N` to choose the next system move. Exit the interface with `<ESC>`.
```

to this will help anyone else who comes across this project.

```
## Running The Simulation Interface

Once built, load all the core libraries and examples with following command and pressing enter.

$ stack repl

Then run the simulator of the corresponding distributed application as follows:

> runGUI DPC.Examples.AppName.initNetwork

where `AppName` is, e.g., `Calculator.Calculator` or `DistributedLocking`. Use digits `1-N` to choose the next system move. Exit the interface with `<ESC>`.
```

I can make a PR if that is acceptable.

**Comment by kandersen** [comment]
Thank you for giving this a spin, and even more so for catching this.

By all means make a PR, I will merge it ASAP!
